name: WordPress Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 100.25.31.178 >> ~/.ssh/known_hosts

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx mysql-server php-fpm php-mysql php-cli

      - name: Download and Configure WordPress
        run: |
          wget https://wordpress.org/latest.tar.gz
          tar -xzvf latest.tar.gz
          sudo mv wordpress /var/www/html/wordpress

      - name: Set Up MySQL Database
        run: |
          sudo mysql -u root -e "CREATE DATABASE wordpress_db;"
          sudo mysql -u root -e "CREATE USER 'wordpress_user'@'localhost' IDENTIFIED BY 'your_password';"
          sudo mysql -u root -e "GRANT ALL PRIVILEGES ON wordpress_db.* TO 'wordpress_user'@'localhost';"
          sudo mysql -u root -e "FLUSH PRIVILEGES;"

      - name: Configure WordPress wp-config.php
        run: |
          sudo cp /var/www/html/wordpress/wp-config.php /var/www/html/wordpress/wp-config.php
          sudo nano  sed -i 's/wordpress_db/' /var/www/html/wordpress/wp-config.php
          sudo nano sed -i 's/wordpress_user/' /var/www/html/wordpress/wp-config.php
          sudo nano sed -i 's/your_password/' /var/www/html/wordpress/wp-config.php

      - name: Configure Nginx for WordPress
        run: |
          sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/wordpress
          sudo sed -i 's/wordpresstask.zapto.org/' /etc/nginx/sites-available/wordpress
          sudo sed -i 's|/var/www/html|/var/www/html/wordpress|' /etc/nginx/sites-available/wordpress
          sudo ln -s /etc/nginx/sites-available/wordpress /etc/nginx/sites-enabled/
          sudo nginx -t
          sudo systemctl reload nginx

      - name: Install Let's Encrypt and Obtain SSL Certificate
        run: |
          sudo apt-get install -y certbot python3-certbot-nginx
          sudo certbot --nginx -d wordpresstask.zapto.org --non-interactive --agree-tos -m monabommakanti@gmail.com

      - name: Restart Nginx with SSL
        run: |
          sudo systemctl restart nginx

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
